# Generated by Django 4.1.2 on 2023-01-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='blogimages')),
                ('model', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
