# Generated by Django 4.1.3 on 2022-12-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_addresstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addresstype',
            new_name='address',
        ),
    ]
